### ISSUE TITLE
Introduce array.prototype.clone

### ISSUE THREAD

**Issue by onygami** [rricard/proposal-change-array-by-copy#11]
Instead of creating a new immutable versions of methods that already exist, could we not introduce a single `.clone()` method that returns a copy of the array that can be mutated safely. 

This can be used in conjunction with all existing functions and instead on introducing a new function for each use case. As developer it would reduce cognitive overload, since you're likely to get confused by naming scheme with the `ed` suffix.

**Comment by zloirock** [comment]
We already have it - `.slice()`. But it will not it doesn't save us from other problems.

**Comment by zloirock** [comment]
From proposed methods, `.slice()` enougth only for `.reduce()` and `.sort()` - the rest methods will return something else, not a modified clone of original array.

**Comment by rricard** [comment]
Yes exactly, thanks @zloirock !
