### ISSUE TITLE
Spec needs `%` for intrinsics

### ISSUE THREAD

**Issue by ljharb** [rricard/proposal-change-array-by-copy#5]
`3. Perform ? Call(Array.prototype.sort, A, «compareFn»).`, for example, needs to be `3. Perform ? Call(%Array.prototype.sort%, A, «compareFn»).`

**Comment by rricard** [comment]
Thanks for pointing out. Will try to fix soon.

**Comment by rricard** [comment]
Given #7, that might become a non-issue
