### ISSUE TITLE
spec calling into mutator methods

### ISSUE THREAD

**Issue by ljharb** [rricard/proposal-change-array-by-copy#7]
For example, http://www.rricard.me/proposal-change-array-by-copy/#sec-array.prototype.spliced calls into the original `splice` directly. However, the original includes an explicit setting of "length", which the [note](https://tc39.es/ecma262/#sec-array.prototype.splice) says is only for legacy reasons. Should that legacy set be avoided in this new method?

**Comment by rricard** [comment]
I will probably follow your recommendation here: the first draft has been quickly thrown together but ultimately I do not expect to keep calling the mutator methods, I have 2 options right now to evolve that spec text that I could use your advice on:

- Recreate a bespoke algorithm for each 'd method
- Factor out more parts of the existing array prototype methods so they are reusable within the 'd methods

I don't know which would be preferred but in either case we could only keep that legacy behavior on the splice function.

**Comment by ljharb** [comment]
Given the likelihood for unintentionally propagating legacy behavior, a process that might be worth following is to create a bespoke algorithm for each one, and then, compare to the mutator algorithm and see if, and what, common parts could be factored out.

**Comment by rricard** [comment]
Sounds like a plan to me!
