### ISSUE TITLE
without: remove elements from array?

### ISSUE THREAD

**Issue by slorber** [rricard/proposal-change-array-by-copy#9]
Hi,

This proposal looks great and would be happy to see these methods added to JS

However, there is one method that I feel is always lacking in JS and is a very common usecase: remove item(s) from an array by value/identity. Just suggestion if this can be considered as part of this proposal?

In UI development we often need to "toggle" values in list, for example let's consider a tag selection UI:

```js 
function toggleTag(tagList,tag)  {
  return tagList.includes(tag) ? tagList.concat(tag) : tagList.filter(t => t !== tag)
}
```

Using `_.without(tagList,tag)` looks more expressive, particularly when you need to remove multiple values at once.

Also think this method would play well with records in a tuple as it would work with tags like`#{name: "TagName", id: "tagId"}`

This is just an idea, just close if this is not the good place to ask for this ;)

**Comment by ljharb** [comment]
This proposal is adding non-mutating forms of existing methods, it’s not adding new methods.

Given that filter covers this use case, i think “without” or similar would need its own proposal.

**Comment by rricard** [comment]
A case can be made because `.with` is the equivalent of an assignment. Maybe `.without` would be the equivalent of a `delete`. However we wouldn't be able to bring that back to tuples: holes are impossible in tuples, and I am not sure we should encourage more holes in arrays either. I think the debate is worth having but I do align with Jordan here...

**Comment by rricard** [comment]
Or yes, a separate proposal could actually be fine, I'll close for now...

**Comment by ljharb** [comment]
To be clear, `_.without(x, y)` does not create holes, it's literally sugar for `x.filter(v => v !== y)` (is my understanding)

**Comment by rricard** [comment]
yes that is why I am closing, it doesn't have a mutator equivalent and creating a  mutator equivalent to `delete` does not make sense
